
package geomatrix.presentation.swing;

import java.awt.BorderLayout;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import manticore.presentation.SwingController;

/**
 *
 * @author Nil
 */
public class MainFrame extends javax.swing.JFrame {

    private MapPanel mapPanel;
    private SwingController swing;
    
    //here will be stored the input of the translate dialog.
    //I don't know how to pass these values more properly when
    //the dialog menu is the same for all areas.
    private int xTranslate;
    private int yTranslate;
    private int areaNumberTranslate;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(SwingController swing) { 
        initComponents();
        this.swing = swing;
        initMapPanel();
        pack();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        translateDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xFieldTranslateDialog = new javax.swing.JTextField();
        yFieldTranslateDialog = new javax.swing.JTextField();
        okButtonTranslateDialog = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        selectArea1 = new javax.swing.JRadioButton();
        selectArea2 = new javax.swing.JRadioButton();
        selectArea3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        displayArea1 = new javax.swing.JToggleButton();
        displayArea2 = new javax.swing.JToggleButton();
        displayArea3 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        area1Menu = new javax.swing.JMenu();
        area1New = new javax.swing.JMenuItem();
        area1Clone = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        area1Union = new javax.swing.JMenu();
        area1UnionArea2 = new javax.swing.JMenuItem();
        area1UnionArea3 = new javax.swing.JMenuItem();
        area1Intersection = new javax.swing.JMenu();
        area1IntersectionArea2 = new javax.swing.JMenuItem();
        area1IntersectionArea3 = new javax.swing.JMenuItem();
        area1Difference = new javax.swing.JMenu();
        area1DifferenceArea2 = new javax.swing.JMenuItem();
        area1DifferenceArea3 = new javax.swing.JMenuItem();
        area1SymmetricDifference = new javax.swing.JMenu();
        area1SymmetricDifferenceArea2 = new javax.swing.JMenuItem();
        area1SymmetricDifferenceArea3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        area1Translate = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        area1Rotate90 = new javax.swing.JMenuItem();
        area1Rotate180 = new javax.swing.JMenuItem();
        area1Rotate270 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        area1ShowRectangleDecomposition = new javax.swing.JCheckBoxMenuItem();
        area1ShowBoundingRectangle = new javax.swing.JCheckBoxMenuItem();
        area2Menu = new javax.swing.JMenu();
        area2New = new javax.swing.JMenuItem();
        area2Clone = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        area2Union = new javax.swing.JMenu();
        area2UnionArea1 = new javax.swing.JMenuItem();
        area2UnionArea3 = new javax.swing.JMenuItem();
        area2Intersection = new javax.swing.JMenu();
        area2IntersectionArea1 = new javax.swing.JMenuItem();
        area2IntersectionArea3 = new javax.swing.JMenuItem();
        area2Difference = new javax.swing.JMenu();
        area2DifferenceArea1 = new javax.swing.JMenuItem();
        area2DifferenceArea3 = new javax.swing.JMenuItem();
        area2SymmetricDifference = new javax.swing.JMenu();
        area2SymmetricDifferenceArea1 = new javax.swing.JMenuItem();
        area2SymmetricDifferenceArea3 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        area2Translate = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        area2Rotate90 = new javax.swing.JMenuItem();
        area2Rotate180 = new javax.swing.JMenuItem();
        area2Rotate270 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        area2ShowRectangleDecomposition = new javax.swing.JCheckBoxMenuItem();
        area2ShowBoundingRectangle = new javax.swing.JCheckBoxMenuItem();
        area3Menu = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        area3Union = new javax.swing.JMenu();
        area3UnionArea1 = new javax.swing.JMenuItem();
        area3UnionArea2 = new javax.swing.JMenuItem();
        area3Intersection = new javax.swing.JMenu();
        area3IntersectionArea1 = new javax.swing.JMenuItem();
        area3IntersectionArea2 = new javax.swing.JMenuItem();
        area3Difference = new javax.swing.JMenu();
        area3DifferenceArea1 = new javax.swing.JMenuItem();
        area3DifferenceArea2 = new javax.swing.JMenuItem();
        area3SymmetricDifference = new javax.swing.JMenu();
        area3SymmetricDifferenceArea1 = new javax.swing.JMenuItem();
        area3SymmetricDifferenceArea2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        area3Translate = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        area3Rotate90 = new javax.swing.JMenuItem();
        area3Rotate180 = new javax.swing.JMenuItem();
        area3Rotate270 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        area3ShowRectangleDecomposition = new javax.swing.JCheckBoxMenuItem();
        area3ShowBoundingRectangle = new javax.swing.JCheckBoxMenuItem();

        jMenuItem4.setText("jMenuItem4");

        translateDialog.setTitle("Translate");
        translateDialog.setMinimumSize(new java.awt.Dimension(185, 133));
        translateDialog.setPreferredSize(new java.awt.Dimension(185, 125));

        jLabel1.setText("x:");

        jLabel2.setText("y:");

        xFieldTranslateDialog.setText("0");

        yFieldTranslateDialog.setText("0");

        okButtonTranslateDialog.setText("OK");
        okButtonTranslateDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonTranslateDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout translateDialogLayout = new javax.swing.GroupLayout(translateDialog.getContentPane());
        translateDialog.getContentPane().setLayout(translateDialogLayout);
        translateDialogLayout.setHorizontalGroup(
            translateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(translateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(translateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, translateDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButtonTranslateDialog))
                    .addGroup(translateDialogLayout.createSequentialGroup()
                        .addGroup(translateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(translateDialogLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xFieldTranslateDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(translateDialogLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yFieldTranslateDialog)))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        translateDialogLayout.setVerticalGroup(
            translateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(translateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(translateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xFieldTranslateDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(translateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(yFieldTranslateDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(okButtonTranslateDialog)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geomatrix");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Select"));

        selectArea1.setBackground(java.awt.Color.red);
        buttonGroup1.add(selectArea1);
        selectArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea1.setSelected(true);
        selectArea1.setText("Area 1");
        selectArea1.setToolTipText("Set Area 1 as selected area");
        selectArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea1ActionPerformed(evt);
            }
        });

        selectArea2.setBackground(new java.awt.Color(0, 51, 255));
        buttonGroup1.add(selectArea2);
        selectArea2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea2.setText("Area 2");
        selectArea2.setToolTipText("Set Area 2 as selected area");
        selectArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea2ActionPerformed(evt);
            }
        });

        selectArea3.setBackground(new java.awt.Color(0, 204, 0));
        buttonGroup1.add(selectArea3);
        selectArea3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea3.setText("Area 3");
        selectArea3.setToolTipText("Set Area 3 as selected area");
        selectArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectArea1)
                    .addComponent(selectArea3)
                    .addComponent(selectArea2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {selectArea1, selectArea2, selectArea3});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectArea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectArea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectArea3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Display"));

        displayArea1.setForeground(java.awt.Color.red);
        displayArea1.setSelected(true);
        displayArea1.setText("Area 1");
        displayArea1.setToolTipText("Display Area 1");
        displayArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea1ActionPerformed(evt);
            }
        });

        displayArea2.setForeground(new java.awt.Color(0, 51, 255));
        displayArea2.setSelected(true);
        displayArea2.setText("Area 2");
        displayArea2.setToolTipText("Display area 2");
        displayArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea2ActionPerformed(evt);
            }
        });

        displayArea3.setForeground(new java.awt.Color(0, 153, 0));
        displayArea3.setSelected(true);
        displayArea3.setText("Area 3");
        displayArea3.setToolTipText("Display area 3");
        displayArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayArea1)
                    .addComponent(displayArea2)
                    .addComponent(displayArea3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {displayArea1, displayArea2, displayArea3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(displayArea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayArea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayArea3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        area1Menu.setText("Area 1");
        area1Menu.setToolTipText("");

        area1New.setText("New");
        area1New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1New(evt);
            }
        });
        area1Menu.add(area1New);

        area1Clone.setText("Clone");

        jMenuItem2.setText("Area 2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1CloneArea2(evt);
            }
        });
        area1Clone.add(jMenuItem2);

        jMenuItem3.setText("Area 3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1CloneArea3(evt);
            }
        });
        area1Clone.add(jMenuItem3);

        area1Menu.add(area1Clone);
        area1Menu.add(jSeparator1);

        area1Union.setText("Union");

        area1UnionArea2.setText("Area 2");
        area1UnionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1UnionArea2(evt);
            }
        });
        area1Union.add(area1UnionArea2);

        area1UnionArea3.setText("Area 3");
        area1UnionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1UnionArea3(evt);
            }
        });
        area1Union.add(area1UnionArea3);

        area1Menu.add(area1Union);

        area1Intersection.setText("Intersection");

        area1IntersectionArea2.setText("Area 2");
        area1IntersectionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1IntersectionArea2ActionPerformed(evt);
            }
        });
        area1Intersection.add(area1IntersectionArea2);

        area1IntersectionArea3.setText("Area 3");
        area1IntersectionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1IntersectionArea3ActionPerformed(evt);
            }
        });
        area1Intersection.add(area1IntersectionArea3);

        area1Menu.add(area1Intersection);

        area1Difference.setText("Difference");

        area1DifferenceArea2.setText("Area 2");
        area1DifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1DifferenceArea2ActionPerformed(evt);
            }
        });
        area1Difference.add(area1DifferenceArea2);

        area1DifferenceArea3.setText("Area 3");
        area1DifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1DifferenceArea3ActionPerformed(evt);
            }
        });
        area1Difference.add(area1DifferenceArea3);

        area1Menu.add(area1Difference);

        area1SymmetricDifference.setText("Symmetric difference");

        area1SymmetricDifferenceArea2.setText("Area 2");
        area1SymmetricDifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1SymmetricDifferenceArea2ActionPerformed(evt);
            }
        });
        area1SymmetricDifference.add(area1SymmetricDifferenceArea2);

        area1SymmetricDifferenceArea3.setText("Area 3");
        area1SymmetricDifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1SymmetricDifferenceArea3ActionPerformed(evt);
            }
        });
        area1SymmetricDifference.add(area1SymmetricDifferenceArea3);

        area1Menu.add(area1SymmetricDifference);
        area1Menu.add(jSeparator2);

        area1Translate.setText("Translate");
        area1Translate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1TranslateActionPerformed(evt);
            }
        });
        area1Menu.add(area1Translate);

        jMenu1.setText("Rotate");

        area1Rotate90.setText("90º");
        area1Rotate90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1Rotate90ActionPerformed(evt);
            }
        });
        jMenu1.add(area1Rotate90);

        area1Rotate180.setText("180º");
        area1Rotate180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1Rotate180ActionPerformed(evt);
            }
        });
        jMenu1.add(area1Rotate180);

        area1Rotate270.setText("270º");
        area1Rotate270.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1Rotate270ActionPerformed(evt);
            }
        });
        jMenu1.add(area1Rotate270);

        area1Menu.add(jMenu1);
        area1Menu.add(jSeparator3);

        area1ShowRectangleDecomposition.setText("Show rectangle decomposition");
        area1ShowRectangleDecomposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1ShowRectangleDecompositionActionPerformed(evt);
            }
        });
        area1Menu.add(area1ShowRectangleDecomposition);

        area1ShowBoundingRectangle.setText("Show bounding rectangle");
        area1ShowBoundingRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1ShowBoundingRectangleActionPerformed(evt);
            }
        });
        area1Menu.add(area1ShowBoundingRectangle);

        jMenuBar1.add(area1Menu);

        area2Menu.setText("Area 2");

        area2New.setText("New");
        area2New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2New(evt);
            }
        });
        area2Menu.add(area2New);

        area2Clone.setText("Clone");

        jMenuItem36.setText("Area 1");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2CloneArea1(evt);
            }
        });
        area2Clone.add(jMenuItem36);

        jMenuItem37.setText("Area 3");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2CloneArea3(evt);
            }
        });
        area2Clone.add(jMenuItem37);

        area2Menu.add(area2Clone);
        area2Menu.add(jSeparator10);

        area2Union.setText("Union");

        area2UnionArea1.setText("Area 1");
        area2UnionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2UnionArea1ActionPerformed(evt);
            }
        });
        area2Union.add(area2UnionArea1);

        area2UnionArea3.setText("Area 3");
        area2UnionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2UnionArea3ActionPerformed(evt);
            }
        });
        area2Union.add(area2UnionArea3);

        area2Menu.add(area2Union);

        area2Intersection.setText("Intersection");

        area2IntersectionArea1.setText("Area 1");
        area2IntersectionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2IntersectionArea1ActionPerformed(evt);
            }
        });
        area2Intersection.add(area2IntersectionArea1);

        area2IntersectionArea3.setText("Area 3");
        area2IntersectionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2IntersectionArea3ActionPerformed(evt);
            }
        });
        area2Intersection.add(area2IntersectionArea3);

        area2Menu.add(area2Intersection);

        area2Difference.setText("Difference");

        area2DifferenceArea1.setText("Area 1");
        area2DifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2DifferenceArea1ActionPerformed(evt);
            }
        });
        area2Difference.add(area2DifferenceArea1);

        area2DifferenceArea3.setText("Area 3");
        area2DifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2DifferenceArea3ActionPerformed(evt);
            }
        });
        area2Difference.add(area2DifferenceArea3);

        area2Menu.add(area2Difference);

        area2SymmetricDifference.setText("Symmetric difference");

        area2SymmetricDifferenceArea1.setText("Area 1");
        area2SymmetricDifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2SymmetricDifferenceArea1ActionPerformed(evt);
            }
        });
        area2SymmetricDifference.add(area2SymmetricDifferenceArea1);

        area2SymmetricDifferenceArea3.setText("Area 3");
        area2SymmetricDifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2SymmetricDifferenceArea3ActionPerformed(evt);
            }
        });
        area2SymmetricDifference.add(area2SymmetricDifferenceArea3);

        area2Menu.add(area2SymmetricDifference);
        area2Menu.add(jSeparator11);

        area2Translate.setText("Translate");
        area2Translate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2TranslateActionPerformed(evt);
            }
        });
        area2Menu.add(area2Translate);

        jMenu2.setText("Rotate");

        area2Rotate90.setText("90º");
        area2Rotate90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2Rotate90ActionPerformed(evt);
            }
        });
        jMenu2.add(area2Rotate90);

        area2Rotate180.setText("180º");
        area2Rotate180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2Rotate180ActionPerformed(evt);
            }
        });
        jMenu2.add(area2Rotate180);

        area2Rotate270.setText("270º");
        area2Rotate270.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2Rotate270ActionPerformed(evt);
            }
        });
        jMenu2.add(area2Rotate270);

        area2Menu.add(jMenu2);
        area2Menu.add(jSeparator7);

        area2ShowRectangleDecomposition.setText("Show rectangle decomposition");
        area2ShowRectangleDecomposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2ShowRectangleDecompositionActionPerformed(evt);
            }
        });
        area2Menu.add(area2ShowRectangleDecomposition);

        area2ShowBoundingRectangle.setText("Show bounding rectangle");
        area2ShowBoundingRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2ShowBoundingRectangleActionPerformed(evt);
            }
        });
        area2Menu.add(area2ShowBoundingRectangle);

        jMenuBar1.add(area2Menu);

        area3Menu.setText("Area 3");

        jMenuItem13.setText("New");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3New(evt);
            }
        });
        area3Menu.add(jMenuItem13);

        jMenu10.setText("Clone");

        jMenuItem14.setText("Area 1");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3CloneArea1(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuItem15.setText("Area 2");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3CloneArea2(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        area3Menu.add(jMenu10);
        area3Menu.add(jSeparator4);

        area3Union.setText("Union");

        area3UnionArea1.setText("Area 1");
        area3UnionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3UnionArea1ActionPerformed(evt);
            }
        });
        area3Union.add(area3UnionArea1);

        area3UnionArea2.setText("Area 2");
        area3UnionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3UnionArea2ActionPerformed(evt);
            }
        });
        area3Union.add(area3UnionArea2);

        area3Menu.add(area3Union);

        area3Intersection.setText("Intersection");

        area3IntersectionArea1.setText("Area 1");
        area3IntersectionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3IntersectionArea1ActionPerformed(evt);
            }
        });
        area3Intersection.add(area3IntersectionArea1);

        area3IntersectionArea2.setText("Area 2");
        area3IntersectionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3IntersectionArea2ActionPerformed(evt);
            }
        });
        area3Intersection.add(area3IntersectionArea2);

        area3Menu.add(area3Intersection);

        area3Difference.setText("Difference");

        area3DifferenceArea1.setText("Area 1");
        area3DifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3DifferenceArea1ActionPerformed(evt);
            }
        });
        area3Difference.add(area3DifferenceArea1);

        area3DifferenceArea2.setText("Area 2");
        area3DifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3DifferenceArea2ActionPerformed(evt);
            }
        });
        area3Difference.add(area3DifferenceArea2);

        area3Menu.add(area3Difference);

        area3SymmetricDifference.setText("Symmetric difference");

        area3SymmetricDifferenceArea1.setText("Area 1");
        area3SymmetricDifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3SymmetricDifferenceArea1ActionPerformed(evt);
            }
        });
        area3SymmetricDifference.add(area3SymmetricDifferenceArea1);

        area3SymmetricDifferenceArea2.setText("Area 2");
        area3SymmetricDifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3SymmetricDifferenceArea2ActionPerformed(evt);
            }
        });
        area3SymmetricDifference.add(area3SymmetricDifferenceArea2);

        area3Menu.add(area3SymmetricDifference);
        area3Menu.add(jSeparator5);

        area3Translate.setText("Translate");
        area3Translate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3TranslateActionPerformed(evt);
            }
        });
        area3Menu.add(area3Translate);

        jMenu3.setText("Rotate");

        area3Rotate90.setText("90º");
        area3Rotate90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3Rotate90ActionPerformed(evt);
            }
        });
        jMenu3.add(area3Rotate90);

        area3Rotate180.setText("180º");
        area3Rotate180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3Rotate180ActionPerformed(evt);
            }
        });
        jMenu3.add(area3Rotate180);

        area3Rotate270.setText("270º");
        area3Rotate270.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3Rotate270ActionPerformed(evt);
            }
        });
        jMenu3.add(area3Rotate270);

        area3Menu.add(jMenu3);
        area3Menu.add(jSeparator8);

        area3ShowRectangleDecomposition.setText("Show rectangle decomposition");
        area3ShowRectangleDecomposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3ShowRectangleDecompositionActionPerformed(evt);
            }
        });
        area3Menu.add(area3ShowRectangleDecomposition);

        area3ShowBoundingRectangle.setText("Show bounding rectangle");
        area3ShowBoundingRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3ShowBoundingRectangleActionPerformed(evt);
            }
        });
        area3Menu.add(area3ShowBoundingRectangle);

        jMenuBar1.add(area3Menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea1ActionPerformed
        mapPanel.setSelected(1);
        displayArea1.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea1ActionPerformed

    private void displayArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea1ActionPerformed
        try {
            if (displayArea1.isSelected()) mapPanel.setDisplayed(1, true);
            else mapPanel.setDisplayed(1, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea1.setSelected(true);
        }
    }//GEN-LAST:event_displayArea1ActionPerformed

    private void displayArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea2ActionPerformed
        try {
            if (displayArea2.isSelected()) mapPanel.setDisplayed(2, true);
            else mapPanel.setDisplayed(2, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea2.setSelected(true);
        }
    }//GEN-LAST:event_displayArea2ActionPerformed

    private void displayArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea3ActionPerformed
        try {
            if (displayArea3.isSelected()) mapPanel.setDisplayed(3, true);
            else mapPanel.setDisplayed(3, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea3.setSelected(true);
        }
    }//GEN-LAST:event_displayArea3ActionPerformed

    private void selectArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea2ActionPerformed
        mapPanel.setSelected(2);
        displayArea2.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea2ActionPerformed

    private void selectArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea3ActionPerformed
        mapPanel.setSelected(3);
        displayArea3.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea3ActionPerformed

    private void area1CloneArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1CloneArea3
        mapPanel.cloneArea(1,3);
    }//GEN-LAST:event_area1CloneArea3

    private void area1UnionArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1UnionArea2
        mapPanel.unionArea(1,2);
    }//GEN-LAST:event_area1UnionArea2

    private void area2New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2New
        mapPanel.resetArea(2);
    }//GEN-LAST:event_area2New

    private void area3UnionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3UnionArea1ActionPerformed
        mapPanel.unionArea(3,1);
    }//GEN-LAST:event_area3UnionArea1ActionPerformed

    private void area3DifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3DifferenceArea2ActionPerformed
        mapPanel.differenceArea(3,2);
    }//GEN-LAST:event_area3DifferenceArea2ActionPerformed

    private void area3New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3New
        mapPanel.resetArea(3);
    }//GEN-LAST:event_area3New

    private void area1New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1New
        mapPanel.resetArea(1);
    }//GEN-LAST:event_area1New

    private void area1CloneArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1CloneArea2
        mapPanel.cloneArea(1,2);
    }//GEN-LAST:event_area1CloneArea2

    private void area2CloneArea1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2CloneArea1
        mapPanel.cloneArea(2,1);
    }//GEN-LAST:event_area2CloneArea1

    private void area2CloneArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2CloneArea3
        mapPanel.cloneArea(2,3);
    }//GEN-LAST:event_area2CloneArea3

    private void area3CloneArea1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3CloneArea1
        mapPanel.cloneArea(3,1);
    }//GEN-LAST:event_area3CloneArea1

    private void area3CloneArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3CloneArea2
        mapPanel.cloneArea(2,3);
    }//GEN-LAST:event_area3CloneArea2

    private void area1UnionArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1UnionArea3
        mapPanel.unionArea(1,3);
    }//GEN-LAST:event_area1UnionArea3

    private void area2UnionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2UnionArea1ActionPerformed
        mapPanel.unionArea(2,1);
    }//GEN-LAST:event_area2UnionArea1ActionPerformed

    private void area2UnionArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2UnionArea3ActionPerformed
        mapPanel.unionArea(2,3);
    }//GEN-LAST:event_area2UnionArea3ActionPerformed

    private void area3UnionArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3UnionArea2ActionPerformed
        mapPanel.unionArea(3,2);
    }//GEN-LAST:event_area3UnionArea2ActionPerformed

    private void area1IntersectionArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1IntersectionArea2ActionPerformed
        mapPanel.intersectionArea(1,2);
    }//GEN-LAST:event_area1IntersectionArea2ActionPerformed

    private void area1IntersectionArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1IntersectionArea3ActionPerformed
         mapPanel.intersectionArea(1,3);
    }//GEN-LAST:event_area1IntersectionArea3ActionPerformed

    private void area2IntersectionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2IntersectionArea1ActionPerformed
         mapPanel.intersectionArea(2,1);
    }//GEN-LAST:event_area2IntersectionArea1ActionPerformed

    private void area2IntersectionArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2IntersectionArea3ActionPerformed
         mapPanel.intersectionArea(2,3);
    }//GEN-LAST:event_area2IntersectionArea3ActionPerformed

    private void area3IntersectionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3IntersectionArea1ActionPerformed
         mapPanel.intersectionArea(3,1);
    }//GEN-LAST:event_area3IntersectionArea1ActionPerformed

    private void area3IntersectionArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3IntersectionArea2ActionPerformed
         mapPanel.intersectionArea(3,2);
    }//GEN-LAST:event_area3IntersectionArea2ActionPerformed

    private void area1DifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1DifferenceArea2ActionPerformed
        mapPanel.differenceArea(1,2);
    }//GEN-LAST:event_area1DifferenceArea2ActionPerformed

    private void area1DifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1DifferenceArea3ActionPerformed
        mapPanel.differenceArea(1,3);
    }//GEN-LAST:event_area1DifferenceArea3ActionPerformed

    private void area2DifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2DifferenceArea1ActionPerformed
        mapPanel.differenceArea(2,1);
    }//GEN-LAST:event_area2DifferenceArea1ActionPerformed

    private void area2DifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2DifferenceArea3ActionPerformed
        mapPanel.differenceArea(2,3);
    }//GEN-LAST:event_area2DifferenceArea3ActionPerformed

    private void area3DifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3DifferenceArea1ActionPerformed
        mapPanel.differenceArea(3,1);
    }//GEN-LAST:event_area3DifferenceArea1ActionPerformed

    private void area1SymmetricDifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1SymmetricDifferenceArea2ActionPerformed
        mapPanel.symmetricDifferenceArea(1,2);
    }//GEN-LAST:event_area1SymmetricDifferenceArea2ActionPerformed

    private void area1SymmetricDifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1SymmetricDifferenceArea3ActionPerformed
        mapPanel.symmetricDifferenceArea(1,3);
    }//GEN-LAST:event_area1SymmetricDifferenceArea3ActionPerformed

    private void area2SymmetricDifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2SymmetricDifferenceArea1ActionPerformed
        mapPanel.symmetricDifferenceArea(2,1);
    }//GEN-LAST:event_area2SymmetricDifferenceArea1ActionPerformed

    private void area2SymmetricDifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2SymmetricDifferenceArea3ActionPerformed
        mapPanel.symmetricDifferenceArea(2,3);
    }//GEN-LAST:event_area2SymmetricDifferenceArea3ActionPerformed

    private void area3SymmetricDifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3SymmetricDifferenceArea1ActionPerformed
        mapPanel.symmetricDifferenceArea(3,1);
    }//GEN-LAST:event_area3SymmetricDifferenceArea1ActionPerformed

    private void area3SymmetricDifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3SymmetricDifferenceArea2ActionPerformed
        mapPanel.symmetricDifferenceArea(3,2);
    }//GEN-LAST:event_area3SymmetricDifferenceArea2ActionPerformed

    private void area1ShowRectangleDecompositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1ShowRectangleDecompositionActionPerformed
        throw new UnsupportedOperationException("No algorithm has been found for this problem yet.");
    }//GEN-LAST:event_area1ShowRectangleDecompositionActionPerformed

    private void area2ShowRectangleDecompositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2ShowRectangleDecompositionActionPerformed
        throw new UnsupportedOperationException("No algorithm has been found for this problem yet.");
    }//GEN-LAST:event_area2ShowRectangleDecompositionActionPerformed

    private void area3ShowRectangleDecompositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3ShowRectangleDecompositionActionPerformed
        throw new UnsupportedOperationException("No algorithm has been found for this problem yet.");
    }//GEN-LAST:event_area3ShowRectangleDecompositionActionPerformed

    private void area1ShowBoundingRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1ShowBoundingRectangleActionPerformed
        if (area1ShowBoundingRectangle.isSelected()) {
            mapPanel.showBoundingRectangle(1, true);
        }
        else {
            mapPanel.showBoundingRectangle(1, false);
        }
    }//GEN-LAST:event_area1ShowBoundingRectangleActionPerformed

    private void area2ShowBoundingRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2ShowBoundingRectangleActionPerformed
        if (area2ShowBoundingRectangle.isSelected()) {
            mapPanel.showBoundingRectangle(2, true);
        }
        else {
            mapPanel.showBoundingRectangle(2, false);
        }
    }//GEN-LAST:event_area2ShowBoundingRectangleActionPerformed

    private void area3ShowBoundingRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3ShowBoundingRectangleActionPerformed
        if (area3ShowBoundingRectangle.isSelected()) {
            mapPanel.showBoundingRectangle(3, true);
        }
        else {
            mapPanel.showBoundingRectangle(3, false);
        }
    }//GEN-LAST:event_area3ShowBoundingRectangleActionPerformed

    private void area1TranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1TranslateActionPerformed
        translateDialog.setVisible(true);
        areaNumberTranslate = 1;
    }//GEN-LAST:event_area1TranslateActionPerformed

    private void okButtonTranslateDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonTranslateDialogActionPerformed
        okButtonTranslateDialog.setSelected(false);
        xTranslate = Integer.parseInt(xFieldTranslateDialog.getText());
        yTranslate = Integer.parseInt(yFieldTranslateDialog.getText());
        xFieldTranslateDialog.setText("0");
        yFieldTranslateDialog.setText("0");
        translateDialog.setVisible(false);
        mapPanel.translateArea(areaNumberTranslate, xTranslate, yTranslate);
    }//GEN-LAST:event_okButtonTranslateDialogActionPerformed

    private void area2TranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2TranslateActionPerformed
        translateDialog.setVisible(true);
        areaNumberTranslate = 2;
    }//GEN-LAST:event_area2TranslateActionPerformed

    private void area3TranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3TranslateActionPerformed
        translateDialog.setVisible(true);
        areaNumberTranslate = 3;
    }//GEN-LAST:event_area3TranslateActionPerformed

    private void area1Rotate90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1Rotate90ActionPerformed
        mapPanel.rotateArea(1, 90);
    }//GEN-LAST:event_area1Rotate90ActionPerformed

    private void area1Rotate180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1Rotate180ActionPerformed
        mapPanel.rotateArea(1, 180);
    }//GEN-LAST:event_area1Rotate180ActionPerformed

    private void area1Rotate270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1Rotate270ActionPerformed
        mapPanel.rotateArea(1, 270);
    }//GEN-LAST:event_area1Rotate270ActionPerformed

    private void area2Rotate90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2Rotate90ActionPerformed
        mapPanel.rotateArea(2, 90);
    }//GEN-LAST:event_area2Rotate90ActionPerformed

    private void area2Rotate180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2Rotate180ActionPerformed
        mapPanel.rotateArea(2, 180);
    }//GEN-LAST:event_area2Rotate180ActionPerformed

    private void area2Rotate270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2Rotate270ActionPerformed
        mapPanel.rotateArea(2, 270);
    }//GEN-LAST:event_area2Rotate270ActionPerformed

    private void area3Rotate90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3Rotate90ActionPerformed
        mapPanel.rotateArea(3, 90);
    }//GEN-LAST:event_area3Rotate90ActionPerformed

    private void area3Rotate180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3Rotate180ActionPerformed
        mapPanel.rotateArea(3, 180);
    }//GEN-LAST:event_area3Rotate180ActionPerformed

    private void area3Rotate270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3Rotate270ActionPerformed
        mapPanel.rotateArea(3, 270);
    }//GEN-LAST:event_area3Rotate270ActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu area1Clone;
    private javax.swing.JMenu area1Difference;
    private javax.swing.JMenuItem area1DifferenceArea2;
    private javax.swing.JMenuItem area1DifferenceArea3;
    private javax.swing.JMenu area1Intersection;
    private javax.swing.JMenuItem area1IntersectionArea2;
    private javax.swing.JMenuItem area1IntersectionArea3;
    private javax.swing.JMenu area1Menu;
    private javax.swing.JMenuItem area1New;
    private javax.swing.JMenuItem area1Rotate180;
    private javax.swing.JMenuItem area1Rotate270;
    private javax.swing.JMenuItem area1Rotate90;
    private javax.swing.JCheckBoxMenuItem area1ShowBoundingRectangle;
    private javax.swing.JCheckBoxMenuItem area1ShowRectangleDecomposition;
    private javax.swing.JMenu area1SymmetricDifference;
    private javax.swing.JMenuItem area1SymmetricDifferenceArea2;
    private javax.swing.JMenuItem area1SymmetricDifferenceArea3;
    private javax.swing.JMenuItem area1Translate;
    private javax.swing.JMenu area1Union;
    private javax.swing.JMenuItem area1UnionArea2;
    private javax.swing.JMenuItem area1UnionArea3;
    private javax.swing.JMenu area2Clone;
    private javax.swing.JMenu area2Difference;
    private javax.swing.JMenuItem area2DifferenceArea1;
    private javax.swing.JMenuItem area2DifferenceArea3;
    private javax.swing.JMenu area2Intersection;
    private javax.swing.JMenuItem area2IntersectionArea1;
    private javax.swing.JMenuItem area2IntersectionArea3;
    private javax.swing.JMenu area2Menu;
    private javax.swing.JMenuItem area2New;
    private javax.swing.JMenuItem area2Rotate180;
    private javax.swing.JMenuItem area2Rotate270;
    private javax.swing.JMenuItem area2Rotate90;
    private javax.swing.JCheckBoxMenuItem area2ShowBoundingRectangle;
    private javax.swing.JCheckBoxMenuItem area2ShowRectangleDecomposition;
    private javax.swing.JMenu area2SymmetricDifference;
    private javax.swing.JMenuItem area2SymmetricDifferenceArea1;
    private javax.swing.JMenuItem area2SymmetricDifferenceArea3;
    private javax.swing.JMenuItem area2Translate;
    private javax.swing.JMenu area2Union;
    private javax.swing.JMenuItem area2UnionArea1;
    private javax.swing.JMenuItem area2UnionArea3;
    private javax.swing.JMenu area3Difference;
    private javax.swing.JMenuItem area3DifferenceArea1;
    private javax.swing.JMenuItem area3DifferenceArea2;
    private javax.swing.JMenu area3Intersection;
    private javax.swing.JMenuItem area3IntersectionArea1;
    private javax.swing.JMenuItem area3IntersectionArea2;
    private javax.swing.JMenu area3Menu;
    private javax.swing.JMenuItem area3Rotate180;
    private javax.swing.JMenuItem area3Rotate270;
    private javax.swing.JMenuItem area3Rotate90;
    private javax.swing.JCheckBoxMenuItem area3ShowBoundingRectangle;
    private javax.swing.JCheckBoxMenuItem area3ShowRectangleDecomposition;
    private javax.swing.JMenu area3SymmetricDifference;
    private javax.swing.JMenuItem area3SymmetricDifferenceArea1;
    private javax.swing.JMenuItem area3SymmetricDifferenceArea2;
    private javax.swing.JMenuItem area3Translate;
    private javax.swing.JMenu area3Union;
    private javax.swing.JMenuItem area3UnionArea1;
    private javax.swing.JMenuItem area3UnionArea2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton displayArea1;
    private javax.swing.JToggleButton displayArea2;
    private javax.swing.JToggleButton displayArea3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToggleButton okButtonTranslateDialog;
    private javax.swing.JRadioButton selectArea1;
    private javax.swing.JRadioButton selectArea2;
    private javax.swing.JRadioButton selectArea3;
    private javax.swing.JDialog translateDialog;
    private javax.swing.JTextField xFieldTranslateDialog;
    private javax.swing.JTextField yFieldTranslateDialog;
    // End of variables declaration//GEN-END:variables

    private void initMapPanel() {
        mapPanel = swing.get(MapPanel.class);
        mapPanel.setMainFrame(this);
        add(mapPanel, BorderLayout.CENTER);
        mapPanel.setVisible(true);
        pack();
    }

    void enableSetOperations(int areaNumber, boolean isValid) {
        assert(areaNumber >= 1 && areaNumber <= 3);
        
        if (areaNumber == 1) {
            area1Union.setEnabled(isValid);
            area1Intersection.setEnabled(isValid);
            area1Difference.setEnabled(isValid);
            area1SymmetricDifference.setEnabled(isValid);
            
            area2UnionArea1.setEnabled(isValid);
            area2IntersectionArea1.setEnabled(isValid);
            area2DifferenceArea1.setEnabled(isValid);
            area2SymmetricDifferenceArea1.setEnabled(isValid);
            
            area3UnionArea1.setEnabled(isValid);
            area3IntersectionArea1.setEnabled(isValid);
            area3DifferenceArea1.setEnabled(isValid);
            area3SymmetricDifferenceArea1.setEnabled(isValid);
        }
        else if (areaNumber == 2) {
            area2Union.setEnabled(isValid);
            area2Intersection.setEnabled(isValid);
            area2Difference.setEnabled(isValid);
            area2SymmetricDifference.setEnabled(isValid);
            
            area1UnionArea2.setEnabled(isValid);
            area1IntersectionArea2.setEnabled(isValid);
            area1DifferenceArea2.setEnabled(isValid);
            area1SymmetricDifferenceArea2.setEnabled(isValid);
            
            area3UnionArea2.setEnabled(isValid);
            area3IntersectionArea2.setEnabled(isValid);
            area3DifferenceArea2.setEnabled(isValid);
            area3SymmetricDifferenceArea2.setEnabled(isValid);            
        }
        else if (areaNumber == 3) {
            area3Union.setEnabled(isValid);
            area3Intersection.setEnabled(isValid);
            area3Difference.setEnabled(isValid);
            area3SymmetricDifference.setEnabled(isValid);
            
            area1UnionArea3.setEnabled(isValid);
            area1IntersectionArea3.setEnabled(isValid);
            area1DifferenceArea3.setEnabled(isValid);
            area1SymmetricDifferenceArea3.setEnabled(isValid);
            
            area2UnionArea3.setEnabled(isValid);
            area2IntersectionArea3.setEnabled(isValid);
            area2DifferenceArea3.setEnabled(isValid);
            area2SymmetricDifferenceArea3.setEnabled(isValid);            
        }
    }
}
