
package geomatrix.presentation.swing;

import java.awt.BorderLayout;
import manticore.presentation.SwingController;

/**
 *
 * @author Nil
 */
public class MainFrame extends javax.swing.JFrame {

    private MapPanel mapPanel;
    private SwingController swing;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(SwingController swing) { 
        initComponents();
        this.swing = swing;
        initMapPanel();
        pack();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        selectArea1 = new javax.swing.JRadioButton();
        selectArea2 = new javax.swing.JRadioButton();
        selectArea3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        displayArea1 = new javax.swing.JToggleButton();
        displayArea2 = new javax.swing.JToggleButton();
        displayArea3 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        area1Union = new javax.swing.JMenu();
        area1UnionArea2 = new javax.swing.JMenuItem();
        area1UnionArea3 = new javax.swing.JMenuItem();
        area1Intersection = new javax.swing.JMenu();
        area1IntersectionArea2 = new javax.swing.JMenuItem();
        area1IntersectionArea3 = new javax.swing.JMenuItem();
        area1Difference = new javax.swing.JMenu();
        area1DifferenceArea2 = new javax.swing.JMenuItem();
        area1DifferenceArea3 = new javax.swing.JMenuItem();
        area1SymmetricDifference = new javax.swing.JMenu();
        area1SymmetricDifferenceArea2 = new javax.swing.JMenuItem();
        area1SymmetricDifferenceArea3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        area2Union = new javax.swing.JMenu();
        area2UnionArea1 = new javax.swing.JMenuItem();
        area2UnionArea3 = new javax.swing.JMenuItem();
        area2Intersection = new javax.swing.JMenu();
        area2IntersectionArea1 = new javax.swing.JMenuItem();
        area2IntersectionArea3 = new javax.swing.JMenuItem();
        area2Difference = new javax.swing.JMenu();
        area2DifferenceArea1 = new javax.swing.JMenuItem();
        area2DifferenceArea3 = new javax.swing.JMenuItem();
        area2SymmetricDifference = new javax.swing.JMenu();
        area2SymmetricDifferenceArea1 = new javax.swing.JMenuItem();
        area2SymmetricDifferenceArea3 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        area3Union = new javax.swing.JMenu();
        area3UnionArea1 = new javax.swing.JMenuItem();
        area3UnionArea2 = new javax.swing.JMenuItem();
        area3Intersection = new javax.swing.JMenu();
        area3IntersectionArea1 = new javax.swing.JMenuItem();
        area3IntersectionArea2 = new javax.swing.JMenuItem();
        area3Difference = new javax.swing.JMenu();
        area3DifferenceArea1 = new javax.swing.JMenuItem();
        area3DifferenceArea2 = new javax.swing.JMenuItem();
        area3SymmetricDifference = new javax.swing.JMenu();
        area3SymmetricDifferenceArea1 = new javax.swing.JMenuItem();
        area3SymmetricDifferenceArea2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geomatrix");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Select"));

        selectArea1.setBackground(java.awt.Color.red);
        buttonGroup1.add(selectArea1);
        selectArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea1.setSelected(true);
        selectArea1.setText("Area 1");
        selectArea1.setToolTipText("Set Area 1 as selected area");
        selectArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea1ActionPerformed(evt);
            }
        });

        selectArea2.setBackground(new java.awt.Color(0, 51, 255));
        buttonGroup1.add(selectArea2);
        selectArea2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea2.setText("Area 2");
        selectArea2.setToolTipText("Set Area 2 as selected area");
        selectArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea2ActionPerformed(evt);
            }
        });

        selectArea3.setBackground(new java.awt.Color(0, 204, 0));
        buttonGroup1.add(selectArea3);
        selectArea3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea3.setText("Area 3");
        selectArea3.setToolTipText("Set Area 3 as selected area");
        selectArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectArea1)
                    .addComponent(selectArea3)
                    .addComponent(selectArea2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {selectArea1, selectArea2, selectArea3});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectArea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectArea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectArea3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Display"));

        displayArea1.setForeground(java.awt.Color.red);
        displayArea1.setSelected(true);
        displayArea1.setText("Area 1");
        displayArea1.setToolTipText("Display Area 1");
        displayArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea1ActionPerformed(evt);
            }
        });

        displayArea2.setForeground(new java.awt.Color(0, 51, 255));
        displayArea2.setSelected(true);
        displayArea2.setText("Area 2");
        displayArea2.setToolTipText("Display area 2");
        displayArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea2ActionPerformed(evt);
            }
        });

        displayArea3.setForeground(new java.awt.Color(0, 153, 0));
        displayArea3.setSelected(true);
        displayArea3.setText("Area 3");
        displayArea3.setToolTipText("Display area 3");
        displayArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayArea1)
                    .addComponent(displayArea2)
                    .addComponent(displayArea3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {displayArea1, displayArea2, displayArea3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(displayArea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayArea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayArea3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("Area 1");
        jMenu1.setToolTipText("");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1New(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu4.setText("Clone");

        jMenuItem2.setText("Area 2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1CloneArea2(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Area 3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1CloneArea3(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator1);

        area1Union.setText("Union");

        area1UnionArea2.setText("Area 2");
        area1UnionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1UnionArea2(evt);
            }
        });
        area1Union.add(area1UnionArea2);

        area1UnionArea3.setText("Area 3");
        area1UnionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1UnionArea3(evt);
            }
        });
        area1Union.add(area1UnionArea3);

        jMenu1.add(area1Union);

        area1Intersection.setText("Intersection");

        area1IntersectionArea2.setText("Area 2");
        area1IntersectionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1IntersectionArea2ActionPerformed(evt);
            }
        });
        area1Intersection.add(area1IntersectionArea2);

        area1IntersectionArea3.setText("Area 3");
        area1IntersectionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1IntersectionArea3ActionPerformed(evt);
            }
        });
        area1Intersection.add(area1IntersectionArea3);

        jMenu1.add(area1Intersection);

        area1Difference.setText("Difference");

        area1DifferenceArea2.setText("Area 2");
        area1DifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1DifferenceArea2ActionPerformed(evt);
            }
        });
        area1Difference.add(area1DifferenceArea2);

        area1DifferenceArea3.setText("Area 3");
        area1DifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1DifferenceArea3ActionPerformed(evt);
            }
        });
        area1Difference.add(area1DifferenceArea3);

        jMenu1.add(area1Difference);

        area1SymmetricDifference.setText("Symmetric difference");

        area1SymmetricDifferenceArea2.setText("Area 2");
        area1SymmetricDifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1SymmetricDifferenceArea2ActionPerformed(evt);
            }
        });
        area1SymmetricDifference.add(area1SymmetricDifferenceArea2);

        area1SymmetricDifferenceArea3.setText("Area 3");
        area1SymmetricDifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1SymmetricDifferenceArea3ActionPerformed(evt);
            }
        });
        area1SymmetricDifference.add(area1SymmetricDifferenceArea3);

        jMenu1.add(area1SymmetricDifference);
        jMenu1.add(jSeparator2);

        jCheckBoxMenuItem1.setText("Show rectangle decomposition");
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setText("Show bounding rectangle");
        jMenu1.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Area 2");

        jMenuItem35.setText("New");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2New(evt);
            }
        });
        jMenu2.add(jMenuItem35);

        jMenu3.setText("Clone");

        jMenuItem36.setText("Area 1");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2CloneArea1(evt);
            }
        });
        jMenu3.add(jMenuItem36);

        jMenuItem37.setText("Area 3");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2CloneArea3(evt);
            }
        });
        jMenu3.add(jMenuItem37);

        jMenu2.add(jMenu3);
        jMenu2.add(jSeparator10);

        area2Union.setText("Union");

        area2UnionArea1.setText("Area 1");
        area2UnionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2UnionArea1ActionPerformed(evt);
            }
        });
        area2Union.add(area2UnionArea1);

        area2UnionArea3.setText("Area 3");
        area2UnionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2UnionArea3ActionPerformed(evt);
            }
        });
        area2Union.add(area2UnionArea3);

        jMenu2.add(area2Union);

        area2Intersection.setText("Intersection");

        area2IntersectionArea1.setText("Area 1");
        area2IntersectionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2IntersectionArea1ActionPerformed(evt);
            }
        });
        area2Intersection.add(area2IntersectionArea1);

        area2IntersectionArea3.setText("Area 3");
        area2IntersectionArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2IntersectionArea3ActionPerformed(evt);
            }
        });
        area2Intersection.add(area2IntersectionArea3);

        jMenu2.add(area2Intersection);

        area2Difference.setText("Difference");

        area2DifferenceArea1.setText("Area 1");
        area2DifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2DifferenceArea1ActionPerformed(evt);
            }
        });
        area2Difference.add(area2DifferenceArea1);

        area2DifferenceArea3.setText("Area 3");
        area2DifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2DifferenceArea3ActionPerformed(evt);
            }
        });
        area2Difference.add(area2DifferenceArea3);

        jMenu2.add(area2Difference);

        area2SymmetricDifference.setText("Symmetric difference");

        area2SymmetricDifferenceArea1.setText("Area 1");
        area2SymmetricDifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2SymmetricDifferenceArea1ActionPerformed(evt);
            }
        });
        area2SymmetricDifference.add(area2SymmetricDifferenceArea1);

        area2SymmetricDifferenceArea3.setText("Area 3");
        area2SymmetricDifferenceArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2SymmetricDifferenceArea3ActionPerformed(evt);
            }
        });
        area2SymmetricDifference.add(area2SymmetricDifferenceArea3);

        jMenu2.add(area2SymmetricDifference);
        jMenu2.add(jSeparator11);

        jCheckBoxMenuItem8.setText("Show rectangle decomposition");
        jMenu2.add(jCheckBoxMenuItem8);

        jCheckBoxMenuItem7.setText("Show bounding rectangle");
        jMenu2.add(jCheckBoxMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu9.setText("Area 3");

        jMenuItem13.setText("New");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3New(evt);
            }
        });
        jMenu9.add(jMenuItem13);

        jMenu10.setText("Clone");

        jMenuItem14.setText("Area 1");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3CloneArea1(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuItem15.setText("Area 2");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3CloneArea2(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        jMenu9.add(jMenu10);
        jMenu9.add(jSeparator4);

        area3Union.setText("Union");

        area3UnionArea1.setText("Area 1");
        area3UnionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3UnionArea1ActionPerformed(evt);
            }
        });
        area3Union.add(area3UnionArea1);

        area3UnionArea2.setText("Area 2");
        area3UnionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3UnionArea2ActionPerformed(evt);
            }
        });
        area3Union.add(area3UnionArea2);

        jMenu9.add(area3Union);

        area3Intersection.setText("Intersection");

        area3IntersectionArea1.setText("Area 1");
        area3IntersectionArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3IntersectionArea1ActionPerformed(evt);
            }
        });
        area3Intersection.add(area3IntersectionArea1);

        area3IntersectionArea2.setText("Area 2");
        area3IntersectionArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3IntersectionArea2ActionPerformed(evt);
            }
        });
        area3Intersection.add(area3IntersectionArea2);

        jMenu9.add(area3Intersection);

        area3Difference.setText("Difference");

        area3DifferenceArea1.setText("Area 1");
        area3DifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3DifferenceArea1ActionPerformed(evt);
            }
        });
        area3Difference.add(area3DifferenceArea1);

        area3DifferenceArea2.setText("Area 2");
        area3DifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3DifferenceArea2ActionPerformed(evt);
            }
        });
        area3Difference.add(area3DifferenceArea2);

        jMenu9.add(area3Difference);

        area3SymmetricDifference.setText("Symmetric difference");

        area3SymmetricDifferenceArea1.setText("Area 1");
        area3SymmetricDifferenceArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3SymmetricDifferenceArea1ActionPerformed(evt);
            }
        });
        area3SymmetricDifference.add(area3SymmetricDifferenceArea1);

        area3SymmetricDifferenceArea2.setText("Area 2");
        area3SymmetricDifferenceArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3SymmetricDifferenceArea2ActionPerformed(evt);
            }
        });
        area3SymmetricDifference.add(area3SymmetricDifferenceArea2);

        jMenu9.add(area3SymmetricDifference);
        jMenu9.add(jSeparator5);

        jCheckBoxMenuItem3.setText("Show rectangle decomposition");
        jMenu9.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setText("Show bounding rectangle");
        jMenu9.add(jCheckBoxMenuItem4);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea1ActionPerformed
        mapPanel.setSelected(1);
        displayArea1.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea1ActionPerformed

    private void displayArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea1ActionPerformed
        try {
            if (displayArea1.isSelected()) mapPanel.setDisplayed(1, true);
            else mapPanel.setDisplayed(1, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea1.setSelected(true);
        }
    }//GEN-LAST:event_displayArea1ActionPerformed

    private void displayArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea2ActionPerformed
        try {
            if (displayArea2.isSelected()) mapPanel.setDisplayed(2, true);
            else mapPanel.setDisplayed(2, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea2.setSelected(true);
        }
    }//GEN-LAST:event_displayArea2ActionPerformed

    private void displayArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea3ActionPerformed
        try {
            if (displayArea3.isSelected()) mapPanel.setDisplayed(3, true);
            else mapPanel.setDisplayed(3, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea3.setSelected(true);
        }
    }//GEN-LAST:event_displayArea3ActionPerformed

    private void selectArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea2ActionPerformed
        mapPanel.setSelected(2);
        displayArea2.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea2ActionPerformed

    private void selectArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea3ActionPerformed
        mapPanel.setSelected(3);
        displayArea3.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea3ActionPerformed

    private void area1CloneArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1CloneArea3
        mapPanel.cloneArea(1,3);
    }//GEN-LAST:event_area1CloneArea3

    private void area1UnionArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1UnionArea2
        mapPanel.unionArea(1,2);
    }//GEN-LAST:event_area1UnionArea2

    private void area2New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2New
        mapPanel.resetArea(2);
    }//GEN-LAST:event_area2New

    private void area3UnionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3UnionArea1ActionPerformed
        mapPanel.unionArea(3,1);
    }//GEN-LAST:event_area3UnionArea1ActionPerformed

    private void area3DifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3DifferenceArea2ActionPerformed
        mapPanel.differenceArea(3,2);
    }//GEN-LAST:event_area3DifferenceArea2ActionPerformed

    private void area3New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3New
        mapPanel.resetArea(3);
    }//GEN-LAST:event_area3New

    private void area1New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1New
        mapPanel.resetArea(1);
    }//GEN-LAST:event_area1New

    private void area1CloneArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1CloneArea2
        mapPanel.cloneArea(1,2);
    }//GEN-LAST:event_area1CloneArea2

    private void area2CloneArea1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2CloneArea1
        mapPanel.cloneArea(2,1);
    }//GEN-LAST:event_area2CloneArea1

    private void area2CloneArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2CloneArea3
        mapPanel.cloneArea(2,3);
    }//GEN-LAST:event_area2CloneArea3

    private void area3CloneArea1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3CloneArea1
        mapPanel.cloneArea(3,1);
    }//GEN-LAST:event_area3CloneArea1

    private void area3CloneArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3CloneArea2
        mapPanel.cloneArea(2,3);
    }//GEN-LAST:event_area3CloneArea2

    private void area1UnionArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1UnionArea3
        mapPanel.unionArea(1,3);
    }//GEN-LAST:event_area1UnionArea3

    private void area2UnionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2UnionArea1ActionPerformed
        mapPanel.unionArea(2,1);
    }//GEN-LAST:event_area2UnionArea1ActionPerformed

    private void area2UnionArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2UnionArea3ActionPerformed
        mapPanel.unionArea(2,3);
    }//GEN-LAST:event_area2UnionArea3ActionPerformed

    private void area3UnionArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3UnionArea2ActionPerformed
        mapPanel.unionArea(3,2);
    }//GEN-LAST:event_area3UnionArea2ActionPerformed

    private void area1IntersectionArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1IntersectionArea2ActionPerformed
        mapPanel.intersectionArea(1,2);
    }//GEN-LAST:event_area1IntersectionArea2ActionPerformed

    private void area1IntersectionArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1IntersectionArea3ActionPerformed
         mapPanel.intersectionArea(1,3);
    }//GEN-LAST:event_area1IntersectionArea3ActionPerformed

    private void area2IntersectionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2IntersectionArea1ActionPerformed
         mapPanel.intersectionArea(2,1);
    }//GEN-LAST:event_area2IntersectionArea1ActionPerformed

    private void area2IntersectionArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2IntersectionArea3ActionPerformed
         mapPanel.intersectionArea(2,3);
    }//GEN-LAST:event_area2IntersectionArea3ActionPerformed

    private void area3IntersectionArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3IntersectionArea1ActionPerformed
         mapPanel.intersectionArea(3,1);
    }//GEN-LAST:event_area3IntersectionArea1ActionPerformed

    private void area3IntersectionArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3IntersectionArea2ActionPerformed
         mapPanel.intersectionArea(3,2);
    }//GEN-LAST:event_area3IntersectionArea2ActionPerformed

    private void area1DifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1DifferenceArea2ActionPerformed
        mapPanel.differenceArea(1,2);
    }//GEN-LAST:event_area1DifferenceArea2ActionPerformed

    private void area1DifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1DifferenceArea3ActionPerformed
        mapPanel.differenceArea(1,3);
    }//GEN-LAST:event_area1DifferenceArea3ActionPerformed

    private void area2DifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2DifferenceArea1ActionPerformed
        mapPanel.differenceArea(2,1);
    }//GEN-LAST:event_area2DifferenceArea1ActionPerformed

    private void area2DifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2DifferenceArea3ActionPerformed
        mapPanel.differenceArea(2,3);
    }//GEN-LAST:event_area2DifferenceArea3ActionPerformed

    private void area3DifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3DifferenceArea1ActionPerformed
        mapPanel.differenceArea(3,1);
    }//GEN-LAST:event_area3DifferenceArea1ActionPerformed

    private void area1SymmetricDifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1SymmetricDifferenceArea2ActionPerformed
        mapPanel.symmetricDifferenceArea(1,2);
    }//GEN-LAST:event_area1SymmetricDifferenceArea2ActionPerformed

    private void area1SymmetricDifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1SymmetricDifferenceArea3ActionPerformed
        mapPanel.symmetricDifferenceArea(1,3);
    }//GEN-LAST:event_area1SymmetricDifferenceArea3ActionPerformed

    private void area2SymmetricDifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2SymmetricDifferenceArea1ActionPerformed
        mapPanel.symmetricDifferenceArea(2,1);
    }//GEN-LAST:event_area2SymmetricDifferenceArea1ActionPerformed

    private void area2SymmetricDifferenceArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2SymmetricDifferenceArea3ActionPerformed
        mapPanel.symmetricDifferenceArea(2,3);
    }//GEN-LAST:event_area2SymmetricDifferenceArea3ActionPerformed

    private void area3SymmetricDifferenceArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3SymmetricDifferenceArea1ActionPerformed
        mapPanel.symmetricDifferenceArea(3,1);
    }//GEN-LAST:event_area3SymmetricDifferenceArea1ActionPerformed

    private void area3SymmetricDifferenceArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3SymmetricDifferenceArea2ActionPerformed
        mapPanel.symmetricDifferenceArea(3,2);
    }//GEN-LAST:event_area3SymmetricDifferenceArea2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu area1Difference;
    private javax.swing.JMenuItem area1DifferenceArea2;
    private javax.swing.JMenuItem area1DifferenceArea3;
    private javax.swing.JMenu area1Intersection;
    private javax.swing.JMenuItem area1IntersectionArea2;
    private javax.swing.JMenuItem area1IntersectionArea3;
    private javax.swing.JMenu area1SymmetricDifference;
    private javax.swing.JMenuItem area1SymmetricDifferenceArea2;
    private javax.swing.JMenuItem area1SymmetricDifferenceArea3;
    private javax.swing.JMenu area1Union;
    private javax.swing.JMenuItem area1UnionArea2;
    private javax.swing.JMenuItem area1UnionArea3;
    private javax.swing.JMenu area2Difference;
    private javax.swing.JMenuItem area2DifferenceArea1;
    private javax.swing.JMenuItem area2DifferenceArea3;
    private javax.swing.JMenu area2Intersection;
    private javax.swing.JMenuItem area2IntersectionArea1;
    private javax.swing.JMenuItem area2IntersectionArea3;
    private javax.swing.JMenu area2SymmetricDifference;
    private javax.swing.JMenuItem area2SymmetricDifferenceArea1;
    private javax.swing.JMenuItem area2SymmetricDifferenceArea3;
    private javax.swing.JMenu area2Union;
    private javax.swing.JMenuItem area2UnionArea1;
    private javax.swing.JMenuItem area2UnionArea3;
    private javax.swing.JMenu area3Difference;
    private javax.swing.JMenuItem area3DifferenceArea1;
    private javax.swing.JMenuItem area3DifferenceArea2;
    private javax.swing.JMenu area3Intersection;
    private javax.swing.JMenuItem area3IntersectionArea1;
    private javax.swing.JMenuItem area3IntersectionArea2;
    private javax.swing.JMenu area3SymmetricDifference;
    private javax.swing.JMenuItem area3SymmetricDifferenceArea1;
    private javax.swing.JMenuItem area3SymmetricDifferenceArea2;
    private javax.swing.JMenu area3Union;
    private javax.swing.JMenuItem area3UnionArea1;
    private javax.swing.JMenuItem area3UnionArea2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton displayArea1;
    private javax.swing.JToggleButton displayArea2;
    private javax.swing.JToggleButton displayArea3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton selectArea1;
    private javax.swing.JRadioButton selectArea2;
    private javax.swing.JRadioButton selectArea3;
    // End of variables declaration//GEN-END:variables

    private void initMapPanel() {
        mapPanel = swing.get(MapPanel.class);
        mapPanel.setMainFrame(this);
        add(mapPanel, BorderLayout.CENTER);
        mapPanel.setVisible(true);
        pack();
    }

    void enableSetOperations(int areaNumber, boolean isValid) {
        assert(areaNumber >= 1 && areaNumber <= 3);
        
        if (areaNumber == 1) {
            area1Union.setEnabled(isValid);
            area1Intersection.setEnabled(isValid);
            area1Difference.setEnabled(isValid);
            area1SymmetricDifference.setEnabled(isValid);
            
            area2UnionArea1.setEnabled(isValid);
            area2IntersectionArea1.setEnabled(isValid);
            area2DifferenceArea1.setEnabled(isValid);
            area2SymmetricDifferenceArea1.setEnabled(isValid);
            
            area3UnionArea1.setEnabled(isValid);
            area3IntersectionArea1.setEnabled(isValid);
            area3DifferenceArea1.setEnabled(isValid);
            area3SymmetricDifferenceArea1.setEnabled(isValid);
        }
        else if (areaNumber == 2) {
            area2Union.setEnabled(isValid);
            area2Intersection.setEnabled(isValid);
            area2Difference.setEnabled(isValid);
            area2SymmetricDifference.setEnabled(isValid);
            
            area1UnionArea2.setEnabled(isValid);
            area1IntersectionArea2.setEnabled(isValid);
            area1DifferenceArea2.setEnabled(isValid);
            area1SymmetricDifferenceArea2.setEnabled(isValid);
            
            area3UnionArea2.setEnabled(isValid);
            area3IntersectionArea2.setEnabled(isValid);
            area3DifferenceArea2.setEnabled(isValid);
            area3SymmetricDifferenceArea2.setEnabled(isValid);            
        }
        else if (areaNumber == 3) {
            area3Union.setEnabled(isValid);
            area3Intersection.setEnabled(isValid);
            area3Difference.setEnabled(isValid);
            area3SymmetricDifference.setEnabled(isValid);
            
            area1UnionArea3.setEnabled(isValid);
            area1IntersectionArea3.setEnabled(isValid);
            area1DifferenceArea3.setEnabled(isValid);
            area1SymmetricDifferenceArea3.setEnabled(isValid);
            
            area2UnionArea3.setEnabled(isValid);
            area2IntersectionArea3.setEnabled(isValid);
            area2DifferenceArea3.setEnabled(isValid);
            area2SymmetricDifferenceArea3.setEnabled(isValid);            
        }
    }
}
