
package geomatrix.presentation.swing;

import java.awt.BorderLayout;
import manticore.presentation.SwingController;

/**
 *
 * @author Nil
 */
public class MainFrame extends javax.swing.JFrame {

    private MapPanel mapPanel;
    private SwingController swing;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(SwingController swing) { 
        initComponents();
        this.swing = swing;
        initMapPanel();
        pack();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        selectArea1 = new javax.swing.JRadioButton();
        selectArea2 = new javax.swing.JRadioButton();
        selectArea3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        displayArea1 = new javax.swing.JToggleButton();
        displayArea2 = new javax.swing.JToggleButton();
        displayArea3 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geomatrix");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Select"));

        selectArea1.setBackground(java.awt.Color.red);
        buttonGroup1.add(selectArea1);
        selectArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea1.setSelected(true);
        selectArea1.setText("Area 1");
        selectArea1.setToolTipText("Set Area 1 as selected area");
        selectArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea1ActionPerformed(evt);
            }
        });

        selectArea2.setBackground(new java.awt.Color(0, 51, 255));
        buttonGroup1.add(selectArea2);
        selectArea2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea2.setText("Area 2");
        selectArea2.setToolTipText("Set Area 2 as selected area");
        selectArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea2ActionPerformed(evt);
            }
        });

        selectArea3.setBackground(new java.awt.Color(0, 204, 0));
        buttonGroup1.add(selectArea3);
        selectArea3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectArea3.setText("Area 3");
        selectArea3.setToolTipText("Set Area 3 as selected area");
        selectArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArea3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectArea1)
                    .addComponent(selectArea3)
                    .addComponent(selectArea2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {selectArea1, selectArea2, selectArea3});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectArea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectArea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectArea3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Display"));

        displayArea1.setForeground(java.awt.Color.red);
        displayArea1.setSelected(true);
        displayArea1.setText("Area 1");
        displayArea1.setToolTipText("Display Area 1");
        displayArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea1ActionPerformed(evt);
            }
        });

        displayArea2.setForeground(new java.awt.Color(0, 51, 255));
        displayArea2.setSelected(true);
        displayArea2.setText("Area 2");
        displayArea2.setToolTipText("Display area 2");
        displayArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea2ActionPerformed(evt);
            }
        });

        displayArea3.setForeground(new java.awt.Color(0, 153, 0));
        displayArea3.setSelected(true);
        displayArea3.setText("Area 3");
        displayArea3.setToolTipText("Display area 3");
        displayArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArea3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayArea1)
                    .addComponent(displayArea2)
                    .addComponent(displayArea3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {displayArea1, displayArea2, displayArea3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(displayArea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayArea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayArea3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("Area 1");
        jMenu1.setToolTipText("");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1New(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu4.setText("Clone");

        jMenuItem2.setText("Area 2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1CloneArea2(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Area 3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1CloneArea3(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);
        jMenu1.add(jSeparator1);

        jMenu5.setText("Union");

        jMenuItem5.setText("Area 2");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Area 3");
        jMenu5.add(jMenuItem6);

        jMenu1.add(jMenu5);

        jMenu6.setText("Intersection");

        jMenuItem7.setText("Area 2");
        jMenu6.add(jMenuItem7);

        jMenuItem8.setText("Area 3");
        jMenu6.add(jMenuItem8);

        jMenu1.add(jMenu6);

        jMenu7.setText("Difference");

        jMenuItem9.setText("Area 2");
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Area 3");
        jMenu7.add(jMenuItem10);

        jMenu1.add(jMenu7);

        jMenu8.setText("Symmetric difference");

        jMenuItem11.setText("Area 2");
        jMenu8.add(jMenuItem11);

        jMenuItem12.setText("Area 3");
        jMenu8.add(jMenuItem12);

        jMenu1.add(jMenu8);
        jMenu1.add(jSeparator2);

        jCheckBoxMenuItem1.setText("Show rectangle decomposition");
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setText("Show bounding rectangle");
        jMenu1.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Area 2");

        jMenuItem35.setText("New");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2New(evt);
            }
        });
        jMenu2.add(jMenuItem35);

        jMenu3.setText("Clone");

        jMenuItem36.setText("Area 1");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2CloneArea1(evt);
            }
        });
        jMenu3.add(jMenuItem36);

        jMenuItem37.setText("Area 3");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2CloneArea3(evt);
            }
        });
        jMenu3.add(jMenuItem37);

        jMenu2.add(jMenu3);
        jMenu2.add(jSeparator10);

        jMenu21.setText("Union");

        jMenuItem38.setText("Area 1");
        jMenu21.add(jMenuItem38);

        jMenuItem39.setText("Area 3");
        jMenu21.add(jMenuItem39);

        jMenu2.add(jMenu21);

        jMenu22.setText("Intersection");

        jMenuItem40.setText("Area 1");
        jMenu22.add(jMenuItem40);

        jMenuItem41.setText("Area 3");
        jMenu22.add(jMenuItem41);

        jMenu2.add(jMenu22);

        jMenu23.setText("Difference");

        jMenuItem42.setText("Area 1");
        jMenu23.add(jMenuItem42);

        jMenuItem43.setText("Area 3");
        jMenu23.add(jMenuItem43);

        jMenu2.add(jMenu23);

        jMenu24.setText("Symmetric difference");

        jMenuItem44.setText("Area 1");
        jMenu24.add(jMenuItem44);

        jMenuItem45.setText("Area 3");
        jMenu24.add(jMenuItem45);

        jMenu2.add(jMenu24);
        jMenu2.add(jSeparator11);

        jCheckBoxMenuItem8.setText("Show rectangle decomposition");
        jMenu2.add(jCheckBoxMenuItem8);

        jCheckBoxMenuItem7.setText("Show bounding rectangle");
        jMenu2.add(jCheckBoxMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu9.setText("Area 3");

        jMenuItem13.setText("New");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3New(evt);
            }
        });
        jMenu9.add(jMenuItem13);

        jMenu10.setText("Clone");

        jMenuItem14.setText("Area 1");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3CloneArea1(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuItem15.setText("Area 2");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3CloneArea2(evt);
            }
        });
        jMenu10.add(jMenuItem15);

        jMenu9.add(jMenu10);
        jMenu9.add(jSeparator4);

        jMenu11.setText("Union");

        jMenuItem16.setText("Area 1");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem16);

        jMenuItem17.setText("Area 2");
        jMenu11.add(jMenuItem17);

        jMenu9.add(jMenu11);

        jMenu12.setText("Intersection");

        jMenuItem18.setText("Area 1");
        jMenu12.add(jMenuItem18);

        jMenuItem19.setText("Area 2");
        jMenu12.add(jMenuItem19);

        jMenu9.add(jMenu12);

        jMenu13.setText("Difference");

        jMenuItem20.setText("Area 1");
        jMenu13.add(jMenuItem20);

        jMenuItem21.setText("Area 2");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem21);

        jMenu9.add(jMenu13);

        jMenu14.setText("Symmetric difference");

        jMenuItem22.setText("Area 1");
        jMenu14.add(jMenuItem22);

        jMenuItem23.setText("Area 2");
        jMenu14.add(jMenuItem23);

        jMenu9.add(jMenu14);
        jMenu9.add(jSeparator5);

        jCheckBoxMenuItem3.setText("Show rectangle decomposition");
        jMenu9.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setText("Show bounding rectangle");
        jMenu9.add(jCheckBoxMenuItem4);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea1ActionPerformed
        mapPanel.setSelected(1);
        displayArea1.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea1ActionPerformed

    private void displayArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea1ActionPerformed
        try {
            if (displayArea1.isSelected()) mapPanel.setDisplayed(1, true);
            else mapPanel.setDisplayed(1, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea1.setSelected(true);
        }
    }//GEN-LAST:event_displayArea1ActionPerformed

    private void displayArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea2ActionPerformed
        try {
            if (displayArea2.isSelected()) mapPanel.setDisplayed(2, true);
            else mapPanel.setDisplayed(2, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea2.setSelected(true);
        }
    }//GEN-LAST:event_displayArea2ActionPerformed

    private void displayArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArea3ActionPerformed
        try {
            if (displayArea3.isSelected()) mapPanel.setDisplayed(3, true);
            else mapPanel.setDisplayed(3, false);
        }
        catch (HideSelectedAreaException e) {
            //do not allow to hide selected area
            displayArea3.setSelected(true);
        }
    }//GEN-LAST:event_displayArea3ActionPerformed

    private void selectArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea2ActionPerformed
        mapPanel.setSelected(2);
        displayArea2.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea2ActionPerformed

    private void selectArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArea3ActionPerformed
        mapPanel.setSelected(3);
        displayArea3.setSelected(true); //a selected area is always displayed
    }//GEN-LAST:event_selectArea3ActionPerformed

    private void area1CloneArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1CloneArea3
        mapPanel.cloneArea(1,3);
    }//GEN-LAST:event_area1CloneArea3

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void area2New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2New
        mapPanel.resetArea(2);
    }//GEN-LAST:event_area2New

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void area3New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3New
        mapPanel.resetArea(3);
    }//GEN-LAST:event_area3New

    private void area1New(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1New
        mapPanel.resetArea(1);
    }//GEN-LAST:event_area1New

    private void area1CloneArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1CloneArea2
        mapPanel.cloneArea(1,2);
    }//GEN-LAST:event_area1CloneArea2

    private void area2CloneArea1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2CloneArea1
        mapPanel.cloneArea(2,1);
    }//GEN-LAST:event_area2CloneArea1

    private void area2CloneArea3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2CloneArea3
        mapPanel.cloneArea(2,3);
    }//GEN-LAST:event_area2CloneArea3

    private void area3CloneArea1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3CloneArea1
        mapPanel.cloneArea(3,1);
    }//GEN-LAST:event_area3CloneArea1

    private void area3CloneArea2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3CloneArea2
        mapPanel.cloneArea(2,3);
    }//GEN-LAST:event_area3CloneArea2

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton displayArea1;
    private javax.swing.JToggleButton displayArea2;
    private javax.swing.JToggleButton displayArea3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton selectArea1;
    private javax.swing.JRadioButton selectArea2;
    private javax.swing.JRadioButton selectArea3;
    // End of variables declaration//GEN-END:variables

    private void initMapPanel() {
        mapPanel = swing.get(MapPanel.class);
        add(mapPanel, BorderLayout.CENTER);
        mapPanel.setVisible(true);
        pack();
    }
}
